# base info
baseURL: "https://blog.dsrkafuu.su"
title: "DSRBLOG"

# features
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
taxonomies:
  tag: "tags"
paginate: 10
disableKinds:
  - "RSS"
googleAnalytics: "G-P3JYXLDF3W"

# language
languageCode: "zh-cn" # rss
defaultContentLanguage: "zh-hans" # html

# params
params:
  mainSections:
    - "post"
    - "code"
  author: "DSRKafuU"
  para: "Internet for people, not profit"
  avatar: "https://cdn.jsdelivr.net/gh/dsrkafuu/dsr-cdn@1/images/avatars/dsrkafuu_256p.webp"
  header: "/images/_header.webp"
  og: "/images/_og.png"
  search: "https://www.google.com"
  license: "本站内容采用 CC BY-NC-SA 4.0 许可，请注明出处；商业转载请联系作者授权。"

# menu
menu:
  main:
    - name: "文章"
      url: "/post/"
      weight: 1
    - name: "笔记"
      url: "/code/"
      weight: 2
    - name: "标签"
      url: "/tags/"
      weight: 3
    - name: "友链"
      url: "/friends/"
      weight: 4
  links:
    - name: "#icon-github"
      url: "https://github.com/dsrkafuu"
      weight: 1
    - name: "#icon-twitter"
      url: "https://twitter.com/dsrkafuu"
      weight: 2
    - name: "#icon-steam"
      url: "https://steamcommunity.com/id/dsrkafuu/"
      weight: 3

# markup
markup:
  goldmark:
    renderer:
      unsafe: true # enable user-embed HTML snippets
  highlight:
    codeFences: false # disable code highlighter
    tabWidth: 2
  tableOfContents:
    startLevel: 2
    endLevel: 3

# build options
build:
  noJSConfigInAssets: true
