# base info
baseURL: "https://amzrk2.cc/"
title: "DSRKafuU"

# features
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
taxonomies:
  tag: "tags"
paginate: 10
disableKinds:
  - "RSS"

# language
languageCode: "zh-cn" # rss
defaultContentLanguage: "zh-hans" # html

# params
params:
  # sidebar info
  author: "DSRKafuU"
  para: "是卡夫"
  avatar: "/images/_wk_256p.webp"
  image: "/images/_header.webp"
  og: "/images/_og.png"
  mainSections:
    - "post"
    - "code"

# menu
menu:
  main:
    - name: "文章"
      url: "/post/"
      weight: 1
    - name: "代码"
      url: "/code/"
      weight: 2
    - name: "标签"
      url: "/tags/"
      weight: 3
    - name: "友链"
      url: "/friends/"
      weight: 4
  links:
    - name: "#icon-github"
      url: "https://github.com/amzrk2"
      weight: 1
    - name: "#icon-twitter"
      url: "https://twitter.com/amzrk2"
      weight: 2
    - name: "#icon-steam"
      url: "https://steamcommunity.com/id/amzrk2/"
      weight: 3

# markup
markup:
  goldmark:
    renderer:
      unsafe: true # enable user-embed HTML snippets
  highlight:
    codeFences: false # disable code highlighter
    tabWidth: 2
  tableOfContents:
    startLevel: 2
    endLevel: 3

# build options
build:
  noJSConfigInAssets: true
